"""Real verification tests for the DICOM viewer flow.

Uses a real DICOM file (tests/sample.dcm, generated by tests/make_sample.py)
— no mocks. Run: pytest tests/ -q
"""
from pathlib import Path

import numpy as np
import pytest
from fastapi.testclient import TestClient

from src.imaging.handler import DICOMHandler

SAMPLE = Path(__file__).parent / "sample.dcm"


def test_read_metadata_real():
    meta = DICOMHandler.read_metadata(str(SAMPLE))
    assert meta["patient_name"] == "Test^Patient"
    assert meta["patient_id"] == "TEST123"
    assert meta["modality"] == "CT"
    assert meta["pixel_spacing"] == [0.5, 0.5]


def test_get_pixel_data_real():
    pixels = DICOMHandler.get_pixel_data(str(SAMPLE))
    assert pixels.shape == (64, 64)
    assert pixels.dtype == np.uint8
    assert pixels.max() == 255  # normalized
    assert pixels.min() >= 0


def test_analyze_endpoint_end_to_end():
    from src.main import app
    client = TestClient(app)
    with open(SAMPLE, "rb") as f:
        r = client.post("/analyze", files={"file": ("sample.dcm", f, "application/dicom")})
    assert r.status_code == 200, r.text
    body = r.json()
    assert body["status"] == "success"
    assert body["metadata"]["patient_id"] == "TEST123"
    assert body["analysis"]["pixel_shape"] == [64, 64]
    seg = body["analysis"]["segmentation"]
    # Either a real UNet inference result, or an honest unavailable notice —
    # never a fake "mock" string.
    assert "mock" not in str(body).lower()
    if seg.get("status") != "unavailable":
        assert 0.0 <= seg["mask_mean"] <= 1.0
        assert 0.0 <= seg["anomaly_score"] <= 1.0


def test_health():
    from src.main import app
    client = TestClient(app)
    r = client.get("/health")
    assert r.status_code == 200
    assert r.json()["status"] == "ok"
